// Prova cliccata delle pagine Agenda e Chat (direzione A, versione 15): la Console e le due tab del telefono.
// Uso (dalla radice o da qualunque cartella): PLAYWRIGHT_MODULE=playwright NODE_PATH=/opt/node22/lib/node_modules LOCAL_FONT_CSS=/percorso/fonts.css node schermate/direzioni/prove/agenda-chat.js
const path = require('path'), fs = require('fs');

const css = process.env.LOCAL_FONT_CSS ? fs.readFileSync(process.env.LOCAL_FONT_CSS, 'utf8') : '';
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const file = q => 'file://' + path.resolve(__dirname, '../direzione-a.html') + (q ? '?' + q : '');
const fileM = q => 'file://' + path.resolve(__dirname, '../mobile.html') + (q ? '?' + q : '');
let ok = 0, ko = 0;
const check = (cond, msg) => { if (cond) { ok++; console.log('  ok  ' + msg); } else { ko++; console.log('  KO  ' + msg); } };
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
  const page = await ctx.newPage();
  await page.route('https://fonts.googleapis.com/**', r => r.fulfill({ status: 200, contentType: 'text/css', body: css }));
  const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  const txt = async sel => (await page.locator(sel).first().textContent()).replace(/\s+/g, ' ').trim();
  const conta = sel => page.locator(sel).count();
  const titolo = () => txt('.a-title');
  const vai = async (q, ms) => { await page.goto(file(q)); await page.waitForTimeout(ms || 400); };
  const clic = async (sel, ms) => { await page.click(sel); await page.waitForTimeout(ms || 250); };
  const largo = () => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth);
  /* il modello della pagina: gli eventi della giornata, i fili e i messaggi */
  const giornata = () => page.evaluate(() => modello.giornata().map(x => ({ chi: x.chi, stato: x.stato, da: x.da })));
  const filo = id => page.evaluate(id => modello.filoDi(modello.byId[id]).map(v => ({ da: v.da, ora: v.ora, testo: v.testo })), id);
  const logTitolare = () => page.locator('.lrow.titolare').allTextContents().then(a => a.map(t => t.replace(/\s+/g, ' ').trim()));

  console.log('1. l\'agenda: dal rail e dalla barra «Oggi in azienda»');
  await vai('tendina=chiusa');
  check(await conta('.a-rail [data-pagina="agenda"]') === 1 && await conta('.a-rail [data-pagina="chat"]') === 1, 'il rail ha i due cerchi nuovi (chat e agenda)');
  await clic('.a-sched .go');
  check(await titolo() === 'AGENDA', 'il cerchio della barra «Oggi in azienda» apre l\'Agenda');
  check(await conta('.a-rail .rb.white') === 1 && await conta('.a-rail [data-pagina="agenda"].white') === 1, 'il quinto cerchio del rail è acceso');
  const ev = await giornata(); console.log('    eventi di oggi:', ev.map(x => x.da + ' ' + x.stato).join(' | '));
  check(ev.length === 8 && await conta('.giorno .blk') === ev.length, 'la barra del giorno ha un blocco per evento (' + ev.length + ')');
  check(await conta('.giorno .pista .ades') === 1 && await txt('.giorno .ades b') === '10:42', 'il segno di «adesso» sulla pista, alle 10:42');
  check(await conta('.giorno .blk.corso') === 3 && await conta('.giorno .blk.errore') === 1 && await conta('.giorno .blk.pianificato') === 3 && await conta('.giorno .blk.attesa') === 1, 'i blocchi portano lo stato: 3 in corso, 1 errore, 3 pianificati, 1 consegnato');
  check((await txt('.a-stats')).replace(/\s/g, '').startsWith('8eventioggi'), 'il primo numero: otto eventi oggi');
  check(await conta('.cards.riga .ncard.task') === ev.length, 'una card per evento');
  check(await conta('.grow') === 7 && (await txt('.grow .gg b')) === 'giovedì', 'sette righe della settimana, la prima è oggi');
  check(await conta('.grow .voce.scadenza, .grow .voce.ritardo') === 2, 'le due scadenze della settimana sono righe della settimana');
  check(await conta('.crow.scad') === 9 && (await txt('.crow.scad .quando')).startsWith('10 set'), 'nove scadenze, la più vicina in testa');
  check(await largo(), 'nessuno sforo orizzontale');

  console.log('2. l\'agenda: le pillole filtrano, i blocchi aprono l\'esecuzione');
  await clic('[data-az="agenda-filtro"][data-v="pianificato"]');
  check(await conta('.cards.riga .ncard.task') === 3 && await conta('[data-az="agenda-filtro"][data-v="pianificato"].on') === 1, 'filtro «Pianificati»: tre card');
  check(await conta('.giorno .blk') === 8, 'la barra del giorno resta intera: il filtro è delle card');
  await clic('[data-az="agenda-filtro"][data-v="errore"]');
  check(await conta('.cards.riga .ncard.task') === 1 && (await txt('.cards.riga .task .tt')) === 'Deploy in staging', 'filtro «Errori»: solo Kim');
  await clic('[data-az="agenda-filtro"][data-v="tutti"]');
  check(await conta('.cards.riga .ncard.task') === 8, 'filtro «Tutti»: le otto card tornano');
  await clic('.giorno .blk >> nth=0');
  check(await titolo() === '200 LEAD E-COMMERCE IN LOMBARDIA', 'un blocco della barra apre la sua esecuzione');
  await vai('pagina=esecuzione&id=2&tendina=chiusa');
  await clic('[data-pagina="agenda"].pill');
  check(await titolo() === 'AGENDA', 'la pillola «Sposta» di un\'esecuzione pianificata apre l\'Agenda');

  console.log('3. la chat: dal rail, dai cerchi «commenta» e dall\'Esecuzione');
  await vai('tendina=chiusa');
  await clic('.a-rail [data-pagina="chat"]');
  check(await titolo() === 'CHAT', 'il quarto cerchio del rail apre la Chat');
  check(await conta('.erow.filo') === 11 && await conta('.erow.filo.on') === 1, 'undici fili, uno aperto');
  const primo = await txt('.erow.filo.on .tx b');
  check(primo === await txt('.ftesta .tx b'), 'il filo aperto è quello acceso nell\'elenco: ' + primo);
  check(await conta('.fcorpo .msg') === 5 && await conta('.fcorpo .qrow') === 2, 'il filo del Social media manager: cinque messaggi e due consegne');
  await clic('.erow.filo >> nth=2');
  const secondo = await txt('.ftesta .tx b');
  check(secondo !== primo && secondo === await txt('.erow.filo.on .tx b'), 'un altro filo si apre: ' + secondo);
  await vai('pagina=home&tendina=chiusa');
  const nomeCard = await txt('.cards.riga .task .who b');
  await clic('.cards.riga .task [data-pagina="chat"] >> nth=0');
  check(await titolo() === 'CHAT', 'il cerchio «commenta» di una card al lavoro apre la Chat');
  check(await txt('.ftesta .tx b') === nomeCard, 'e apre il filo di quel dipendente: ' + nomeCard);
  await vai('pagina=esecuzione&id=4&tendina=chiusa');
  await clic('[data-pagina="chat"].pill');
  check(await titolo() === 'CHAT' && await txt('.ftesta .tx b') === 'Nora', 'la pillola «Scrivi a Nora» dell\'Esecuzione apre il suo filo');
  check(await conta('.fcorpo .msg') === 7, 'il filo di Nora ha sette messaggi');

  console.log('4. la chat: si scrive, si approva, e la nota dell\'Esecuzione entra nel filo');
  await page.fill('.chat input', 'Tieni il tono del post 3');
  await clic('[data-az="chat-invia"]');
  let f = await filo(4);
  check(f.length === 8 && f[7].da === 'io' && f[7].testo === 'Tieni il tono del post 3' && f[7].ora === '10:42', 'la nota del titolare entra nel filo con l\'ora dell\'azienda');
  check(await conta('.fcorpo .msg.io') === 3 && await page.inputValue('.chat input') === '', 'la bolla del titolare è in pagina e la barra si è svuotata');
  check(await conta('.erow.filo.on .nuovi') === 0, 'il filo non ha più messaggi da leggere');
  const attesa0 = await page.evaluate(() => modello.richiesteDi('attesa').length);
  await clic('.fcorpo .qrow [data-az="approva"]');
  check(await page.evaluate(() => modello.richiesteDi('attesa').length) === attesa0 - 1, 'approvare dalla riga della consegna dentro il filo');
  check(await conta('.fcorpo .qrow .chip.lime') === 1, 'la riga mostra l\'esito');
  await vai('pagina=esecuzione&id=4&tendina=chiusa');
  const log0 = await conta('.lrow');
  await page.fill('.chat input', 'Controlla il tono con il cliente'); await page.keyboard.press('Enter'); await page.waitForTimeout(300);
  check(await conta('.lrow') === log0 + 1 && (await logTitolare()).some(t => t.includes('MR: Controlla il tono con il cliente')), 'dalla barra dell\'Esecuzione la nota entra nel log');
  f = await filo(4);
  check(f[f.length - 1].testo === 'Controlla il tono con il cliente' && f[f.length - 1].passo === undefined, 'e la stessa nota entra nel filo della chat');
  await clic('.a-rail [data-pagina="chat"]');
  check((await txt('.erow.filo[data-id="4"]')).includes('Tu: Controlla il tono con il cliente'), 'nell\'elenco il filo di Nora porta l\'ultima nota');
  check(await page.evaluate(() => [...document.querySelectorAll('.erow.filo')].findIndex(r => r.dataset.id === '4') >= document.querySelectorAll('.erow.filo .nuovi').length), 'i fili con messaggi da leggere stanno prima');
  check(await largo() && errors.length === 0, 'nessuno sforo orizzontale, console pulita');

  console.log('5. le due pagine a quaranta');
  await vai('n=40&pagina=agenda&tendina=chiusa', 600);
  const ev40 = await giornata(); console.log('    eventi a 40:', ev40.length);
  check(await conta('.giorno .blk') === ev40.length && await conta('.grow') === 7, 'la barra del giorno e la settimana reggono ' + ev40.length + ' eventi');
  check(await largo(), 'nessuno sforo orizzontale a 40');
  await vai('n=40&pagina=chat&tendina=chiusa', 600);
  check(await conta('.erow.filo') === 40 && await conta('.fcorpo .msg') >= 1, 'quaranta fili, uno aperto');
  check(await largo(), 'nessuno sforo orizzontale nella Chat a 40');

  console.log('6. il telefono: le tab Chat e Agenda');
  const sfori = () => page.evaluate(() => [...document.querySelectorAll('.m-scr')].filter(s => s.scrollWidth > s.clientWidth).length);
  await page.goto(fileM('schermata=4,5,6')); await page.waitForTimeout(600);
  const tel = k => `.m-tel[data-n="${k}"] `;
  check(await conta('.m-tel') === 3 && await page.getAttribute(tel(1) + '.m-scr', 'data-schermata') === '4', 'tre telefoni: chat, filo, agenda');
  check(await txt(tel(1) + '.m-h1') === 'CHAT' && await conta(tel(1) + '.m-coda .qrow.filo') === 11, 'l\'elenco dei fili: undici righe');
  check(await conta(tel(1) + '.m-bnav .tabs .rb.white') === 1, 'la tab Chat è accesa');
  check(await txt(tel(3) + '.m-h1') === 'AGENDA' && await conta(tel(3) + '.m-ev') === 8, 'l\'agenda: una card per evento');
  check(await conta(tel(3) + '.m-coda .m-gg') === 6, 'i sei giorni dopo oggi');
  await clic(tel(1) + '.m-coda .qrow.filo >> nth=1');
  check(await page.getAttribute(tel(1) + '.m-scr', 'data-schermata') === '5', 'una riga apre il filo sullo stesso telefono');
  const chiTel = await txt(tel(1) + '.m-nav .chi b');
  check(chiTel === await txt(tel(2) + '.m-nav .chi b'), 'i telefoni condividono il filo aperto: ' + chiTel);
  await page.fill(tel(1) + 'input[data-campo="mchat"]', 'Va bene così');
  await page.keyboard.press('Enter'); await page.waitForTimeout(300);
  const idTel = await page.evaluate(() => DGT_MOBILE.coda(modello) && modello.fili().length);
  check(await page.evaluate(() => { const f = modello.dipendenti.map(e => modello.filoDi(e)).flat(); return f.filter(v => v.testo === 'Va bene così').length; }) === 1 && idTel === 11, 'il messaggio scritto dal telefono entra nel filo');
  check((await txt(tel(1) + '.m-fili .msg.io:last-of-type .bub')).startsWith('Va bene così'), 'la bolla del titolare è l\'ultima del filo');
  await clic(tel(1) + '[data-az="indietro"]');
  check(await page.getAttribute(tel(1) + '.m-scr', 'data-schermata') === '4', 'indietro torna all\'elenco dei fili');
  await clic(tel(1) + '.m-bnav .tabs .rb >> nth=3');
  check(await page.getAttribute(tel(1) + '.m-scr', 'data-schermata') === '6', 'la tab Agenda apre l\'agenda');
  check(await sfori() === 0, 'nessuno schermo del telefono scorre di lato');
  check(errors.length === 0, 'nessun errore in console: ' + JSON.stringify(errors));
  console.log(`\n${ok} ok, ${ko} ko`);
  await browser.close(); process.exit(ko ? 1 : 0);
})().catch(e => { console.error('FALLITO', e); process.exit(1); });
